---
blank_issues_enabled: true
contact_links:
  - about: "about backend"
    name: "Backend Repository"
    url: "https://github.com/peterhvw"
  - about: "about ebmail"
    name: "ğŸ“© Email"
    url: "https://tinyurl.com/peterhvw"
  - about: "about letter ğŸ«¶ğŸ»"
    name: "ğŸ’¬ Now peters's Issues"
    url: "https://github.com/peterhvw"